import * as React from 'react'
import { v4 as uuidv4 } from 'uuid'

interface LotusProps {
  className?: string;
  leafFill: [string, string];
}

const Lotus: React.FC<LotusProps> = (props) => {
  const { className, leafFill } = props
  return (
    <svg
      className={className}
      viewBox="0 0 800 800"
      xmlns='http://www.w3.org/2000/svg'
    >
      <rect
        className="lotus__background"
        id="lotus__rect"
      />
      <defs>
        <g
          id='a'
        >
          <path
            d='M0 0c133-133 268-133 400 0C268 133 133 133 0 0z'
            fillOpacity='0.07'
          />
        </g>
      </defs>
      <g
        className="lotus__leafs-container"
      >
        <g
          className="lotus__leafs"
        >
          {new Array(36).fill(undefined).map((_, idx) => {
            const key = uuidv4()
            const rotation = idx * 10
            const fill = leafFill[idx % 2]

            return (
              <use
                className="lotus__leaf"
                fill={fill}
                href='#a'
                key={key}
                transform={`rotate(${rotation})`}
              />
            )
          })}
          {/* <use
              fill='#1F5F7B'
              href='#a'
            />
            <use
              fill='#216582'
              href='#a'
              transform='rotate(10)'
            />
            <use
              fill='#236a89'
              href='#a'
              transform='rotate(20)'
            />
            <use
              fill='#266f90'
              href='#a'
              transform='rotate(30)'
            />
            <use
              fill='#287597'
              href='#a'
              transform='rotate(40)'
            />
            <use
              fill='#2a7a9e'
              href='#a'
              transform='rotate(50)'
            />
            <use
              fill='#2c80a5'
              href='#a'
              transform='rotate(60)'
            />
            <use
              fill='#2f85ab'
              href='#a'
              transform='rotate(70)'
            />
            <use
              fill='#318bb2'
              href='#a'
              transform='rotate(80)'
            />
            <use
              fill='#3490b9'
              href='#a'
              transform='rotate(90)'
            />
            <use
              fill='#3695c0'
              href='#a'
              transform='rotate(100)'
            />
            <use
              fill='#399bc6'
              href='#a'
              transform='rotate(110)'
            />
            <use
              fill='#409EC8'
              href='#a'
              transform='rotate(120)'
            />
            <use
              fill='#45a0ca'
              href='#a'
              transform='rotate(130)'
            />
            <use
              fill='#49a3cc'
              href='#a'
              transform='rotate(140)'
            />
            <use
              fill='#4ea5ce'
              href='#a'
              transform='rotate(150)'
            />
            <use
              fill='#53a7d0'
              href='#a'
              transform='rotate(160)'
            />
            <use
              fill='#58aad2'
              href='#a'
              transform='rotate(170)'
            />
            <use
              fill='#5cacd4'
              href='#a'
              transform='rotate(180)'
            />
            <use
              fill='#61afd6'
              href='#a'
              transform='rotate(190)'
            />
            <use
              fill='#66b1d8'
              href='#a'
              transform='rotate(200)'
            />
            <use
              fill='#6bb4da'
              href='#a'
              transform='rotate(210)'
            />
            <use
              fill='#70b6dc'
              href='#a'
              transform='rotate(220)'
            />
            <use
              fill='#75b9dd'
              href='#a'
              transform='rotate(230)'
            />
            <use
              fill='#7ABBDF'
              href='#a'
              transform='rotate(240)'
            />
            <use
              fill='#6db5dc'
              href='#a'
              transform='rotate(250)'
            />
            <use
              fill='#61afd9'
              href='#a'
              transform='rotate(260)'
            />
            <use
              fill='#54a9d5'
              href='#a'
              transform='rotate(270)'
            />
            <use
              fill='#47a3d2'
              href='#a'
              transform='rotate(280)'
            />
            <use
              fill='#3b9dcf'
              href='#a'
              transform='rotate(290)'
            />
            <use
              fill='#3196c8'
              href='#a'
              transform='rotate(300)'
            />
            <use
              fill='#2e8dbb'
              href='#a'
              transform='rotate(310)'
            />
            <use
              fill='#2b84ae'
              href='#a'
              transform='rotate(320)'
            />
            <use
              fill='#287ba2'
              href='#a'
              transform='rotate(330)'
            />
            <use
              fill='#257295'
              href='#a'
              transform='rotate(340)'
            />
            <use
              fill='#226888'
              href='#a'
              transform='rotate(350)'
            /> */}
        </g>
      </g>
    </svg>
  )
}

export default React.memo(Lotus)
