name: Continuous Integration and Deployment

on:
  pull_request:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  cache-keys:
    name: Setup – Cache keys
    runs-on: ubuntu-latest

    outputs:
      build: build-${{ steps.build.outputs.hash }}-v1
      node-modules: node-modules-${{ steps.node-modules.outputs.hash }}-v1

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - id: build
        run: echo "::set-output name=hash::${{ hashFiles('src/**', '**/package.json', '**/package-lock.json') }}"

      - id: node-modules
        run: echo "::set-output name=hash::${{ hashFiles('**/package-lock.json') }}"

  build:
    name: Build
    needs: cache-keys
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: ${{ needs.cache-keys.outputs.node-modules }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium
          cache: npm

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        name: Install dependencies
        run: npm ci

      - name: Get cached build
        id: cached-build
        uses: actions/cache@v2
        with:
          path: |
            dist
          key: ${{ needs.cache-keys.outputs.build }}

      - if: steps.cached-build.outputs.cache-hit != 'true'
        name: Build
        run: npm run build

  test-unit:
    name: Test – Unit
    needs: [cache-keys, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ needs.cache-keys.outputs.node-modules }}

      - name: Run unit tests
        run: npm run test

  deploy:
    name: Deploy - GitHub Pages
    needs: [cache-keys, build, test-unit]
    if: |
      always() &&
      github.ref == 'refs/heads/main' &&
      (needs.test-a11y.result == 'success' || needs.test-a11y.result == 'skipped') &&
      (needs.test-unit.result == 'success' || needs.test-unit.result == 'skipped')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get cached build
        uses: actions/cache@v2
        with:
          path: |
            dist
          key: ${{ needs.cache-keys.outputs.build }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
